### ISSUE TITLE
ClickToAddress already applied to this element!

### ISSUE THREAD

**Issue by mikewright14** [fetchify-dev/clicktoaddress-js-examples#1]
Whenever i try to call new ClickToAddress i will receive an exception that states "ClickToAddress already applied to this element!". I get this when i inline the javascript onto the page or when i compile it into my other javascript.

**Comment by gs-mancs** [comment]
This error can only appear if the element that you set as the "search", already has an active hook for clicktoaddress.
You probably have some code elsewhere on the page that targets the same input element.

Feel free to send a code example to support@craftyclicks.co.uk and I'll quickly take a look.

**Comment by mikewright14** [comment]
Thank you for your quick reply. That is correct when i re-read over it, i am searching by postcode so the search and postcode hook are both used by the same element. Would i need a separate postcode element ?

**Comment by gs-mancs** [comment]
That wouldn't be the source of the problem.

There has to be another call for clickToAddress, with the dom -> search set to the exact same element as the one you're trying to attach the lib right now.

Maybe just expand the minified code and debug where you call this function? (main function or the attach one)

**Comment by mikewright14** [comment]
I have checked and i am not making that call anywhere else. I will double check now but i cannot find that call in any of my files according to the search.

The console error i am receiving is: "cc_c2a.min.js:11 Uncaught TypeError: Cannot read property 'getAttribute' of null".

The call is:
new clickToAddress({
        accessToken: '{my access code}',
           dom: {
            search: 'CustomerPostcode',
            town: 'CustomerTown',
            postcode: 'CustomerPostcode',
            line_1: 'CustomerAddressOne',
            country: 'CustomerCountry'
        },
        domMode: 'id'
    });

I have removed my access code from it though.

**Comment by gs-mancs** [comment]
That error should appear if one of the defined dom elements doesn't exist. (potentially the search one)
The code looks fine.

Sadly there's not much else I can say without actually seeing this in action.
